name: Linux CI

# Controls when the action will run.
on:
  push:
    branches:  'master'

  # Run for all pull requests
  pull_request:
    branches: '*'
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Linux C++11
        working-directory: ./
        run: ./Scripts/BuildScripts/build_ci_linux.sh
      - name: ABI Checker Report Generation
        if: ${{ (github.ref != 'refs/heads/master' && github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'master') }}
        run: ./Scripts/BuildScripts/abi_checker.sh 2 $GITHUB_BASE_REF
      - name: ABI Checker Upload
        uses: actions/upload-artifact@v3
        if: ${{ (github.ref != 'refs/heads/master' && github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'master') }}
        with:
          name: abi-checker-reports
          path: ./build/Debug/lib/compat_reports
